// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjLFT_3GFBgOCLdAMwIRM033PoN9szQ38',
    appId: '1:366724706110:web:25d5fe20ad97e09060066f',
    messagingSenderId: '366724706110',
    projectId: 'eventbridge-ai',
    authDomain: 'eventbridge-ai.firebaseapp.com',
    storageBucket: 'eventbridge-ai.firebasestorage.app',
    measurementId: 'G-Y3XJ2XLW9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIjpzMpLRf_Vd5tp_cYxLOz3No23A5OLk',
    appId: '1:366724706110:android:f28f1a1c55beb8b560066f',
    messagingSenderId: '366724706110',
    projectId: 'eventbridge-ai',
    storageBucket: 'eventbridge-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsKqBmhHb4bGGdVQdVVGaTeKMItECEa0',
    appId: '1:366724706110:ios:90ff986710ed9e9860066f',
    messagingSenderId: '366724706110',
    projectId: 'eventbridge-ai',
    storageBucket: 'eventbridge-ai.firebasestorage.app',
    iosBundleId: 'com.eventbridge.eventbridgeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJsKqBmhHb4bGGdVQdVVGaTeKMItECEa0',
    appId: '1:366724706110:ios:90ff986710ed9e9860066f',
    messagingSenderId: '366724706110',
    projectId: 'eventbridge-ai',
    storageBucket: 'eventbridge-ai.firebasestorage.app',
    iosBundleId: 'com.eventbridge.eventbridgeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjLFT_3GFBgOCLdAMwIRM033PoN9szQ38',
    appId: '1:366724706110:web:693dabaa8c85717a60066f',
    messagingSenderId: '366724706110',
    projectId: 'eventbridge-ai',
    authDomain: 'eventbridge-ai.firebaseapp.com',
    storageBucket: 'eventbridge-ai.firebasestorage.app',
    measurementId: 'G-YBV03C4VK2',
  );
}
