// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJXf-A5M-5o08eLMTbB6Hh3C0dCfwK07E',
    appId: '1:185107161336:web:6516629e46fcaae2ed9b0d', // Extrapolated from Android/iOS pattern if web was not provided, but usually same sender ID
    messagingSenderId: '185107161336',
    projectId: 'eventbridge-483019',
    authDomain: 'eventbridge-483019.firebaseapp.com',
    storageBucket: 'eventbridge-483019.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJXf-A5M-5o08eLMTbB6Hh3C0dCfwK07E',
    appId: '1:185107161336:android:f3312605b8cf7f4aed9b0d',
    messagingSenderId: '185107161336',
    projectId: 'eventbridge-483019',
    storageBucket: 'eventbridge-483019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUD1TLRw9Xx0UvD_Bqed1XskB3i5eBqUs',
    appId: '1:185107161336:ios:fe6055fc1ea856dbed9b0d',
    messagingSenderId: '185107161336',
    projectId: 'eventbridge-483019',
    storageBucket: 'eventbridge-483019.firebasestorage.app',
    iosBundleId: 'com.eventbridge.eventbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUD1TLRw9Xx0UvD_Bqed1XskB3i5eBqUs',
    appId: '1:185107161336:ios:fe6055fc1ea856dbed9b0d',
    messagingSenderId: '185107161336',
    projectId: 'eventbridge-483019',
    storageBucket: 'eventbridge-483019.firebasestorage.app',
    iosBundleId: 'com.eventbridge.eventbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJXf-A5M-5o08eLMTbB6Hh3C0dCfwK07E',
    appId: '1:185107161336:web:6516629e46fcaae2ed9b0d',
    messagingSenderId: '185107161336',
    projectId: 'eventbridge-483019',
    authDomain: 'eventbridge-483019.firebaseapp.com',
    storageBucket: 'eventbridge-483019.firebasestorage.app',
  );
}
