// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrf0vApoO-VZh4lK7igp6FhRhgvuJRyAI',
    appId: '1:210290711848:web:7a92b2d3e918fc96b8041d',
    messagingSenderId: '210290711848',
    projectId: 'eventbridge-34569',
    authDomain: 'eventbridge-34569.firebaseapp.com',
    storageBucket: 'eventbridge-34569.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrf0vApoO-VZh4lK7igp6FhRhgvuJRyAI',
    appId: '1:210290711848:android:4698e8e659367fcab8041d',
    messagingSenderId: '210290711848',
    projectId: 'eventbridge-34569',
    storageBucket: 'eventbridge-34569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfSemhIre-QzglwMeF7bI6DI4EfamTjPg',
    appId: '1:210290711848:ios:550cb3da79517190b8041d',
    messagingSenderId: '210290711848',
    projectId: 'eventbridge-34569',
    storageBucket: 'eventbridge-34569.firebasestorage.app',
    iosBundleId: 'com.eventbridge.eventbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfSemhIre-QzglwMeF7bI6DI4EfamTjPg',
    appId: '1:210290711848:ios:550cb3da79517190b8041d',
    messagingSenderId: '210290711848',
    projectId: 'eventbridge-34569',
    storageBucket: 'eventbridge-34569.firebasestorage.app',
    iosBundleId: 'com.eventbridge.eventbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrf0vApoO-VZh4lK7igp6FhRhgvuJRyAI',
    appId: '1:210290711848:web:7a92b2d3e918fc96b8041d',
    messagingSenderId: '210290711848',
    projectId: 'eventbridge-34569',
    authDomain: 'eventbridge-34569.firebaseapp.com',
    storageBucket: 'eventbridge-34569.firebasestorage.app',
  );
}
